# Models and embeddings
repo_id: "TheBloke/Llama-2-7B-Chat-GGML"
model_file: "llama-2-7b-chat.ggmlv3.q2_K.bin"
embeddings : "sentence-transformers/all-MiniLM-L6-v2"

# Bard Tokens
__Secure-1PSID   : "put your token here"
__Secure-1PSIDCC : "put your token here"
__Secure-1PSIDTS : "put your token here"
